# Site settings
title: Melissa ♡ Seth
email: seth.silesky@gmail.com
description: 'The official wedding site for Melissa H. Dunn and Seth B. Silesky'
baseurl: "/wedding"
# url: "http://melissaandseth.com" # the base hostname & protocol for your site
twitter_username: '@myfriendseth'
# github_username:  jekyll
# google_plus_com: '109485346959707049693'  # Community link
# google_plus_per: '+GDGManagua'
# facebook_app_id: '12345'

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# set in header.html
more_vert:
  option1:
    name: View our registry!
    link:  /registry/

  # option2:
    # name: Facebook
    # link: www.myawesomelink.com
  # option3:
    # name: Cool Option 3
    # link: www.myawesomelink.com

# disqus: true
# disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
